spring:
  application:
    name: orderService
  liquibase:
    change-log: classpath:/db/changelog/db-changelog-master.xml
  datasource:
    url: jdbc:h2:mem:businessServiceDB
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2-console
  cloud:
    function:
      definition: consumer;producer
    stream:
      bindings:
        producer-out-0:
          destination: orders
          producer:
            userNativeEncoding: false
        consumer-in-0:
          destination: orders
          producer:
            userNativeEncoding: false
      kafka:
        bindings:
          producer-out-0:
            producer:
              record-metadata-channel: "order.metadata"
              configuration:
                key.serializer: org.apache.kafka.common.serialization.ByteArraySerializer
                value.serializer: org.apache.kafka.common.serialization.ByteArraySerializer
          consumer-out-0:
            consumer:
              configuration:
                key.serializer: org.apache.kafka.common.serialization.ByteArraySerializer
                value.serializer: org.apache.kafka.common.serialization.ByteArraySerializer
        binder:
          brokers: localhost
          defaultBrokerPort: 9092
          requiredAcks: all
          ackEachRecord: true

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,info,env"
  endpoint:
    health:
      show-details: "always"
#    beans:
#      enabled: true

com:
  learning:
    metrics:
      enabled: false
      logPublishIntervalInSeconds: 10
#      meterWhiteList: "health,http.server.requests,kafka.producer.request.latency.max,kafka.producer.request.size.max"
      meterWhiteList: "*"



