spring:
  application:
    name: order-service
  liquibase:
    change-log: classpath:/db/changelog/db-changelog-master.xml
  datasource:
    url: jdbc:h2:mem:businessServiceDB
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2-console

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,info,env"
  endpoint:
    health:
      show-details: "always"
#    beans:
#      enabled: true

com:
  learning:
    metrics:
      enabled: true
      log-publish-interval-in-seconds: 1
      meters-white-list: "health,http.server.requests,kafka.producer.request.latency.max,kafka.producer.request.size.max"